[phases.setup]
nixPkgs = [
    "pango",
    "fontconfig",
    "libffi",
    "cairo",
    "libgobject-2.0",
    "glib",
    "harfbuzz"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]