[phases.setup]
nixPkgs = [
    "gobject-introspection",
    "harfbuzz",
    "pango",
    "fontconfig",
    "libffi",
    "cairo",
    "pixman",
    "libjpeg",
    "libpng",
    "libtiff",
    "freetype",
    "libxml2",
    "libxslt",
    "zlib"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]